[llm] # llm config
name = "groq:llama-3.3-70b-versatile"
base_url = ""
api_key = "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"
max_tokens = 1024
temperature = 0.0

[file_paths] # Data files names and paths config
src_dir = "C:/Users/pc/Documents/genai-training-pydanticai/data/text_summarizer"
eval_file = "eval/news_short.json"
eval_file_with_response = "eval/news_short_with_response.json"
results_dir = "results"
results_non_llm_metrics_file="report_non_llm_metrics.txt"

[docs] # Document length config
short_doc_threshold = 5000
medium_doc_threshold = 10000
long_doc_threshold = 20000

[chunker] # chunker config
chunk_size = 2048
chunk_overlap = 128

[embedder] # Text embedding Model config
model = "sentence-transformers/all-MiniLM-L6-v2"
token = ""
normalize = true

[logfire] # log fire config
token = "pylf_v2_eu_31577b26-b670-48b3-b5f5-25c1a3e7637d_Vk1YPjv6lqBTf5qlFr15jjTpByJ0L3gjkhRKXgYvZk3Z"
 
[judge_llm] # Evaluator/Judge LLM config
name = "gemma2-9b-it"
base_url = ""
api_key = ""
max_tokens = 1024
temperature = 0.0
prompt = ""